# factor_queries.py

# Domain-tuned SDG factor queries for REDD+, ARR, Agriculture / IFM projects.
# Each SDG has ~50 example sentences to drive embedding-based similarity.

factor_queries = {

    # =========================================================
    # SDG 1 — NO POVERTY
    # =========================================================
    "SDG_1_No_Poverty": {
        "example_sentences": [
            "the project created paid jobs for local community members in forest protection activities",
            "households receive regular cash payments from the project benefit sharing mechanism",
            "income from sustainable forest products has increased for participating families",
            "the project supports alternative livelihoods to reduce dependence on illegal logging",
            "women and men are paid for nursery work and tree planting under the project",
            "the community receives a share of carbon revenue through an agreed benefit sharing plan",
            "microenterprise development grants were provided to poor households in the project area",
            "project activities help reduce income volatility for forest dependent households",
            "vulnerable households reported more stable earnings after joining project activities",
            "the project established village savings and loan associations to support micro businesses",
            "training in small business management helped participants start income generating activities",
            "cash for work programs were implemented for patrolling and fire management tasks",
            "local people receive wages for monitoring and reporting illegal forest activities",
            "the project supports small-scale enterprises based on non timber forest products",
            "poorest households are prioritized in livelihood support programs under the project",
            "payment for ecosystem services contracts provide regular income to enrolled farmers",
            "the project provides financial incentives to discourage land conversion to agriculture",
            "community members earn income from operating tree nurseries",
            "the project provides stipends for community facilitators and local coordinators",
            "local wage rates for forest related work increased due to project interventions",
            "the project reduces extreme poverty by diversifying household income sources",
            "support was provided to establish community run eco tourism services",
            "revenue from eco tourism is shared with local communities through agreed rules",
            "training and start up capital were offered for sustainable beekeeping enterprises",
            "the project finances skills development for alternative livelihood options",
            "households reported being less reliant on distress sale of assets after the project started",
            "income generated from agroforestry plots improves household economic resilience",
            "the project supports community managed woodlots that generate saleable timber",
            "village development funds were established and financed from project revenues",
            "cash transfers are linked to community compliance with forest protection rules",
            "improved access to markets for community forest products increased household earnings",
            "the project helps reduce seasonal unemployment in rural villages",
            "local cooperatives receive financial support to market sustainable commodities",
            "poorer families are exempted from some project related fees and charges",
            "training in value addition improved the prices obtained for forest based products",
            "the project helped negotiate better prices for community produced goods",
            "income from shade grown crops in agroforestry systems contributes to poverty reduction",
            "the project supports climate smart agriculture that increases farm profitability",
            "households use project income to pay for school fees and basic needs",
            "the project supports household level business planning and budgeting training",
            "cash incentives were provided for farmers who conserve forest on their land",
            "local communities receive compensation when access to forest resources is restricted",
            "livelihood grants targeted landless households in the project area",
            "project supported producer groups to improve bargaining power and reduce exploitation",
            "community members report fewer days without food due to project generated income",
            "the project reduces economic pressure to encroach into remaining forest areas",
            "income from sustainable charcoal or fuelwood production replaces illegal activities",
            "the project supports small scale processing of agricultural products for local markets",
            "training in financial literacy helps households manage new income streams responsibly",
            "carbon revenue distribution ensures that low income groups receive tangible benefits",
            "project interventions directly contribute to reducing poverty in participating villages"
        ]
    },

    # =========================================================
    # SDG 2 — ZERO HUNGER
    # =========================================================
    "SDG_2_Zero_Hunger": {
        "example_sentences": [
            "the project promotes climate resilient crops to improve local food security",
            "agroforestry systems provide both timber and food products for households",
            "farmers reported higher crop yields after adopting project recommended practices",
            "training on soil fertility management increased agricultural productivity",
            "the project supports home gardens that diversify household food sources",
            "improved seed varieties were introduced to enhance food production",
            "the project helps reduce crop losses caused by soil erosion",
            "farmers learned conservation agriculture techniques that stabilize yields",
            "integrated crop and tree systems provide regular harvests throughout the year",
            "the project supports small scale irrigation to reduce dependence on rainfall",
            "households report fewer months of food shortage after project interventions",
            "the project promotes intercropping trees with staple crops to improve nutrition",
            "training on post harvest handling reduced food spoilage in the community",
            "the project encourages planting of fruit trees near homesteads for better diets",
            "support was provided to establish community seed banks for resilient varieties",
            "agricultural extension services were strengthened through the project",
            "the project reduces pressure to expand agriculture into forest by intensifying production",
            "farmers participate in demonstration plots showcasing improved agronomic practices",
            "livestock feeding practices were improved to enhance household protein supply",
            "the project supports fish ponds integrated with tree planting for diversified food sources",
            "nutrition education sessions link project activities to better household diets",
            "the project promotes diversified cropping systems to reduce risk of total crop failure",
            "farmers adopt mulching and cover crops to improve soil moisture and yields",
            "community members report increased availability of vegetables from agroforestry plots",
            "technical support was provided for smallholder rice and maize producers",
            "the project strengthens local food systems by supporting producer organizations",
            "households use income from project related work to purchase higher quality food",
            "the project targets food insecure households for priority support",
            "agricultural practices promoted by the project are adapted to local conditions",
            "the project reduces reliance on shifting cultivation that undermines food security",
            "training in pest management helps protect crops from major yield losses",
            "the project improves access to agricultural inputs through group purchasing",
            "community grain storage facilities were improved with project assistance",
            "the project supports agro ecological practices that enhance long term productivity",
            "improved pasture management increases fodder availability for livestock",
            "the project links farmers with buyers for surplus agricultural products",
            "community members report fewer hungry days following project adoption",
            "the project addresses both food production and natural resource conservation",
            "the project promotes drought tolerant crops to cope with changing rainfall patterns",
            "farmer field schools integrate tree planting into food crop systems",
            "the project helps farmers plan crop rotations that maintain soil health",
            "livelihood support includes training for small scale poultry and goat rearing",
            "the project strengthens local seed systems for climate resilient agriculture",
            "soil and water conservation structures protect fields and support better harvests",
            "the project targets undernourished households with combined support packages",
            "interventions reduce the need to clear new land for agriculture to feed families",
            "the project enhances household access to nutrient rich foods through agroforestry",
            "support to home gardens increases the diversity of foods consumed",
            "enhanced agricultural practices contribute directly to reducing hunger",
            "farmers adopt project promoted technologies that stabilize food production over time"
        ]
    },

    # =========================================================
    # SDG 3 — GOOD HEALTH AND WELL-BEING
    # =========================================================
    "SDG_3_Good_Health": {
        "example_sentences": [
            "the project distributes improved cookstoves that reduce indoor air pollution",
            "households report less smoke exposure when using efficient stoves",
            "reduced time spent collecting fuelwood lowers physical strain and injury risk",
            "the project improves water quality by protecting upstream forest areas",
            "reduced contamination of streams lowers incidence of water borne disease",
            "community members report fewer respiratory infections after adopting new stoves",
            "training on hygiene and sanitation was delivered alongside project activities",
            "the project supports latrine construction and improved sanitation in villages",
            "shade and green spaces created by trees improve local microclimate and comfort",
            "the project reduces exposure to landslides that threaten community safety",
            "reforestation activities help stabilize slopes above settlements",
            "community health workers were engaged to raise awareness of smoke related illnesses",
            "nutrition outcomes improved as households grew more diverse food crops",
            "the project supports clean water points protected by catchment restoration",
            "reduced burning of agricultural residues improves ambient air quality",
            "better housing materials were possible with income from project activities",
            "improved household energy systems reduce burn and accident risks",
            "education on safe chemical use in agriculture was provided",
            "the project reduces conflict over resources that can harm community well being",
            "organised fire management reduces harmful wildfire smoke episodes",
            "community members report improved mental well being linked to more secure livelihoods",
            "the project supports awareness campaigns on malaria and vector control",
            "improved drainage around fields and villages reduces disease breeding sites",
            "the project contributed to safer access routes for collecting forest products",
            "less time spent on laborious fuelwood collection frees time for rest and care",
            "income from the project allows households to afford health services",
            "reduced illegal charcoal production lowers health risks for workers",
            "the project encourages use of protective equipment for forestry workers",
            "training on occupational safety was included for nursery and field work teams",
            "the project supports health outreach during community meetings",
            "reduced smoke from slash and burn practices improves regional air quality",
            "health status is monitored as part of social impact assessments",
            "tree planting along watercourses contributes to cleaner drinking water sources",
            "community members report better quality of sleep due to reduced anxiety about income",
            "the project provides information on safe handling of pesticides and fertilizers",
            "improved nutrition from diversified production supports child health",
            "the project strengthens social cohesion which supports mental well being",
            "reduced frequency of destructive flooding lowers injury and death risk",
            "community infrastructure such as footbridges was repaired or maintained",
            "project staff support referrals to health services during field engagement",
            "improved housing and sanitation were reported as secondary project benefits",
            "improved forest cover helps regulate local climate and reduce heat stress",
            "the project encourages safe water storage practices in households",
            "health risks from working in illegal logging decreased as people moved to legal work",
            "the project integrates health messaging into training and awareness campaigns",
            "time saved from more efficient energy use is used for child care and rest",
            "income from the project allows households to purchase medicines when needed",
            "the project indirectly reduces malnutrition by supporting productive systems",
            "reduced exposure to wildfire events improves respiratory and cardiovascular health",
            "overall community well being improved due to safer and more stable livelihoods"
        ]
    },

    # =========================================================
    # SDG 4 — QUALITY EDUCATION
    # =========================================================
    "SDG_4_Quality_Education": {
        "example_sentences": [
            "the project provides training on sustainable forest management to community members",
            "capacity building workshops were held for local farmers on climate smart agriculture",
            "environmental education campaigns were conducted in local schools",
            "the project supports adult literacy programs linked to livelihood training",
            "training of community forest guards includes technical and leadership skills",
            "youth were engaged in internships and apprenticeships related to project activities",
            "the project supports scholarships for children from participating households",
            "school infrastructure was improved with materials financed by project revenues",
            "the project organizes field days to demonstrate improved practices",
            "community members receive training on financial literacy and record keeping",
            "the project developed training manuals on agroforestry techniques",
            "extension staff were trained to deliver climate resilience messages",
            "demonstration plots serve as practical learning sites for farmers",
            "the project conducts awareness sessions on the value of forest conservation",
            "education materials on biodiversity were distributed to local schools",
            "women received targeted training to participate in project decision making",
            "training on nursery management improves technical knowledge in the community",
            "the project supports peer to peer learning among farmer groups",
            "capacity building for local institutions strengthens long term management",
            "youth clubs were supported to carry out environmental activities",
            "the project trains local facilitators who then teach their neighbours",
            "education on land rights and tenure is provided where relevant",
            "the project hosts exchange visits between communities to share lessons",
            "technical training covers topics such as soil conservation and tree spacing",
            "community meetings are used to share information and build knowledge",
            "the project encourages school based tree planting and environmental clubs",
            "training supports community members to understand carbon projects",
            "awareness raising helps communities engage with monitoring and reporting",
            "the project offers training on small enterprise development and marketing",
            "training improves the ability of local leaders to manage community funds",
            "education sessions include information on climate change impacts and responses",
            "project staff mentor local youth in environmental monitoring techniques",
            "the project supports capacity building of local NGOs and community groups",
            "training is provided on safe and effective use of tools and equipment",
            "the project strengthens farmer field schools in the landscape",
            "feedback meetings are used as opportunities to discuss and learn collectively",
            "the project creates learning materials in local languages",
            "training attendance records demonstrate broad participation across groups",
            "project supported training leads to certification for some participants",
            "education on sustainable harvesting helps reduce over exploitation of resources",
            "the project strengthens community ability to negotiate with external actors",
            "local extension services are upgraded with new skills and materials",
            "the project includes awareness on gender equality and social inclusion",
            "communities learn how to collect and use basic environmental data",
            "training modules are adapted to local literacy levels and culture",
            "the project supports continuous learning rather than one off workshops",
            "knowledge gained from the project is shared with neighbouring villages",
            "teachers receive support to integrate forest and climate topics into lessons",
            "educational activities help build long term stewardship of the landscape",
            "the project clearly contributes to improved access to quality learning opportunities"
        ]
    },

    # =========================================================
    # SDG 5 — GENDER EQUALITY
    # =========================================================
    "SDG_5_Gender_Equality": {
        "example_sentences": [
            "women participate meaningfully in project decision making committees",
            "the project sets quotas to ensure women are represented in governance bodies",
            "women received targeted training on leadership and negotiation skills",
            "the project supports women led livelihood groups and cooperatives",
            "income generating activities are designed to be accessible to women",
            "the project conducts gender analysis to understand different needs and roles",
            "women are employed as forest rangers and nursery workers",
            "project meetings are scheduled at times convenient for women caretakers",
            "childcare support is provided to enable women to attend trainings",
            "women have equal opportunity to benefit from project related employment",
            "the project encourages joint decision making within households on resource use",
            "training content addresses harmful gender norms and promotes equality",
            "the project monitors participation of women and men in all activities",
            "women led enterprises receive seed funding through project support",
            "women representatives hold positions on community forest management boards",
            "the project ensures that benefit sharing arrangements are gender responsive",
            "women report increased confidence to speak in public meetings",
            "the project supports access to identification documents for women if needed",
            "gender disaggregated data is collected for all key project indicators",
            "the project addresses barriers that prevent women from accessing land or resources",
            "targeted outreach is conducted to engage women from marginalized groups",
            "women are involved in designing and monitoring safeguard measures",
            "the project encourages equitable division of labour for project related tasks",
            "women receive specific training in financial management and savings",
            "the project creates safe spaces for women to discuss their priorities",
            "mechanisms exist for women to raise grievances and have them addressed",
            "the project supports mentorship programs pairing women with experienced leaders",
            "employment policies prohibit discrimination based on gender",
            "women are prioritized for some positions in community based organizations",
            "the project ensures that information is accessible to women with low literacy",
            "female headed households are not excluded from project benefits",
            "training covers women’s rights and relevant national legislation",
            "women participate in patrols and monitoring activities across the project area",
            "the project reports specific outcomes related to women’s empowerment",
            "women engage in higher value segments of forest product value chains",
            "the project supports time saving technologies that reduce burdens on women",
            "men are engaged to support gender equality and shared responsibilities",
            "the project tracks changes in women’s decision making power over time",
            "women were consulted separately to identify priorities for interventions",
            "benefit sharing mechanisms require that payments reach women as well as men",
            "the project includes indicators related to gender in its results framework",
            "training facilities are designed to be safe and accessible for women",
            "management positions in the project team are open to qualified women",
            "the project encourages women’s participation in landscape level planning",
            "data shows increased number of women in leadership roles due to the project",
            "women’s groups are recognized as key partners in implementation",
            "the project seeks to reduce gender based barriers to accessing resources",
            "women’s perspectives influence how forest rules are developed and enforced",
            "gender equality is clearly integrated into project design and reporting",
            "overall the project contributes to increased opportunities and voice for women"
        ]
    },

    # =========================================================
    # SDG 6 — CLEAN WATER AND SANITATION
    # =========================================================
    "SDG_6_Clean_Water": {
        "example_sentences": [
            "the project protects upstream forest areas that regulate water flow",
            "riparian buffers were restored to reduce sedimentation in rivers",
            "water quality monitoring shows reduced turbidity after reforestation",
            "the project supports rehabilitation of springs used for drinking water",
            "communities report improved reliability of water sources during dry seasons",
            "the project reduces contamination from agricultural runoff into streams",
            "erosion control measures help maintain cleaner water bodies",
            "wetlands were restored to enhance natural water filtration functions",
            "the project raises awareness about protecting catchment areas from degradation",
            "tree planting along riverbanks reduces bank collapse and siltation",
            "the project coordinates with water authorities on catchment management",
            "communities implement rules to prevent pollution of water points",
            "improved sanitation facilities were constructed with project support",
            "hygiene promotion campaigns were delivered alongside water interventions",
            "the project supports rainwater harvesting for household use",
            "reduced deforestation helps stabilize local hydrological cycles",
            "the project encourages proper disposal of agricultural chemicals",
            "households benefit from safer and more accessible drinking water sources",
            "grazing management reduces trampling and contamination of streams",
            "the project helps maintain base flows important for downstream users",
            "restored forest cover in headwaters contributes to improved water supply",
            "community members report fewer conflicts over water during dry periods",
            "the project contributes to integrated water and land management in the area",
            "water points are located and designed to avoid contamination from latrines",
            "training is provided on safe storage of drinking water in households",
            "the project supports fencing off critical water recharge zones",
            "improved management reduces the need to walk long distances for water",
            "the project promotes soil conservation structures that enhance infiltration",
            "community water committees are strengthened through training and support",
            "the project monitors changes in water availability over time",
            "water source protection is integrated into community land use plans",
            "support was provided to repair or maintain existing water infrastructure",
            "the project contributes to maintaining flows important for wetlands and fisheries",
            "communities adopt measures to reduce open defecation near watercourses",
            "the project reduces sediment loads that previously affected downstream users",
            "water use rules are aligned with conservation objectives under the project",
            "changes in land cover linked to the project are associated with clearer streams",
            "the project helps protect drinking water intakes for nearby settlements",
            "community by laws restrict activities that could pollute water sources",
            "the project supports mapping and protection of key aquifer recharge areas",
            "education campaigns emphasize the link between forests and clean water",
            "community members report fewer cases of diarrheal disease after interventions",
            "the project coordinates with sanitation initiatives to maximize health benefits",
            "tree planting in degraded catchments reduces runoff and flash flooding",
            "the project promotes water efficient agricultural practices to reduce pressure",
            "improved forest cover enhances regulation of flows in small streams",
            "water access improvements particularly benefit women and children",
            "the project explicitly reports contributions to safer water and sanitation",
            "overall the project strengthens the resilience of local water resources"
        ]
    },

    # =========================================================
    # SDG 7 — AFFORDABLE AND CLEAN ENERGY
    # =========================================================
    "SDG_7_Clean_Energy": {
        "example_sentences": [
            "the project distributes improved biomass cookstoves to rural households",
            "efficient stoves reduce the amount of fuelwood needed for cooking",
            "households report spending less time collecting firewood after adopting new stoves",
            "the project supports biogas units in farming households using livestock manure",
            "training is provided on installation and maintenance of clean energy technologies",
            "the project reduces reliance on traditional open fires for cooking",
            "fuel efficient stoves reduce pressure on forest resources in the project area",
            "some households use solar lanterns promoted by the project for lighting",
            "the project encourages sustainable charcoal production techniques where relevant",
            "community members report reduced expenditures on purchased fuelwood",
            "improved energy technologies are made available to low income households",
            "the project coordinates with energy access programs in the region",
            "energy needs are assessed as part of the project’s social baseline",
            "improved kilns are introduced to reduce emissions from charcoal production",
            "the project supports small enterprises that supply clean cooking solutions",
            "households adopt stoves that meet recognized clean cooking standards",
            "reduced fuelwood consumption links directly to avoided deforestation",
            "women report feeling safer with reduced need to travel long distances for fuel",
            "demonstrations show how efficient stoves save time and fuel",
            "the project facilitates access to microfinance for clean energy products",
            "clean energy solutions are adapted to local cooking practices",
            "the project tracks adoption rates and correct use of improved stoves",
            "awareness campaigns explain the health and environmental benefits of clean energy",
            "local artisans are trained to produce or repair efficient stoves",
            "community members report less smoke inside homes due to improved stoves",
            "the project explores renewable energy options for community facilities",
            "fuel stacking patterns are assessed to understand real energy use changes",
            "supply chains for clean energy products are strengthened by the project",
            "the project helps ensure affordability through subsidies or payment plans",
            "improved energy access frees up time for education and income activities",
            "the project reports reductions in fuel use per household over time",
            "clean energy technologies are integrated into broader livelihood strategies",
            "the project supports energy efficient dryers for agricultural products",
            "monitoring data show significant reductions in firewood consumption",
            "the project aligns with national clean cooking and energy access strategies",
            "community members participate in choosing appropriate energy options",
            "the project evaluates user satisfaction with clean energy technologies",
            "efficient stoves complement forest conservation by reducing extraction",
            "energy interventions particularly benefit women who manage household cooking",
            "the project considers lifecycle impacts of the energy technologies promoted",
            "support services are available locally to repair clean energy devices",
            "some project sites use solar powered pumps for small irrigation schemes",
            "the project highlights linkages between energy efficiency and forest protection",
            "clean energy options are promoted in both forest and farming households",
            "evidence shows a sustained shift away from traditional three stone fires",
            "training incorporates safe handling of new energy devices and fuels",
            "the project collects user feedback to improve energy interventions",
            "clean energy access is clearly reported as a co benefit of the project",
            "overall interventions contribute to more affordable and sustainable energy use"
        ]
    },

    # =========================================================
    # SDG 8 — DECENT WORK AND ECONOMIC GROWTH
    # =========================================================
    "SDG_8_Decent_Work": {
        "example_sentences": [
            "the project creates formal job opportunities in forest management and monitoring",
            "workers employed by the project receive fair wages and written contracts",
            "occupational health and safety procedures are in place for field staff",
            "the project supports local enterprises involved in nursery and planting services",
            "youth are employed as community monitors and enumerators",
            "training improves skills that are marketable beyond the project",
            "work created by the project is non exploitative and respects labour standards",
            "the project promotes decent working conditions in supported value chains",
            "local service providers are contracted wherever possible to deliver activities",
            "the project contributes to stable employment beyond seasonal farm work",
            "income generating activities are designed to be sustainable over time",
            "employment opportunities are accessible to women and marginalized groups",
            "the project stimulates local economies through purchase of goods and services",
            "entrepreneurship is encouraged through support to small forest based businesses",
            "workers are trained on safe use of equipment and tools",
            "the project supports certification that improves market access and prices",
            "recorded employment data show significant numbers of local people hired",
            "the project fosters long term business models around sustainable landscapes",
            "participants report improved job security as a result of project involvement",
            "the project avoids child labour and monitors compliance with standards",
            "community members are paid for participating in fire management teams",
            "support is provided to help informal producers transition to formal businesses",
            "the project sets clear expectations and grievance mechanisms for workers",
            "labour policies align with national legislation and good practice",
            "employment practices are transparent and inclusive",
            "project facilitation improves links between producers and formal markets",
            "skills gained through training increase employability in related sectors",
            "the project supports diversification of income sources beyond subsistence farming",
            "cash flows from project activities contribute to local economic growth",
            "some project activities strengthen tourism based employment in the area",
            "participating households report more stable and predictable income from work",
            "youth unemployment declines in communities engaged in the project",
            "the project encourages savings and investment among workers and participants",
            "employment created does not undermine environmental objectives",
            "the project supports formalization of community forestry enterprises",
            "workers receive protective equipment and training on its correct use",
            "the project provides opportunities for advancement and promotion in roles",
            "economic benefits are spread across different segments of the community",
            "support services such as accounting and business planning are provided",
            "the project helps reduce reliance on illegal or unsustainable income sources",
            "monitoring includes indicators for decent work and local economic impacts",
            "local administration recognizes the project as contributing to rural development",
            "the project strengthens value chains for sustainable agricultural commodities",
            "community members report pride in stable and dignified employment",
            "support to producer organizations enhances bargaining power and earnings",
            "the project strengthens links between producers and responsible buyers",
            "income from project related work helps households invest in productive assets",
            "the project reports long term viability of employment and enterprises created",
            "overall the project contributes to decent work and more resilient local economies"
        ]
    },

    # =========================================================
    # SDG 9 — INDUSTRY, INNOVATION AND INFRASTRUCTURE
    # =========================================================
    "SDG_9_Industry_Innovation_Infrastructure": {
        "example_sentences": [
            "the project supports small processing facilities for agricultural or forest products",
            "value addition activities such as drying and packaging are introduced",
            "the project improves rural feeder roads used to access markets",
            "innovative monitoring technologies are tested in the project area",
            "the project promotes improved kilns or equipment for efficient production",
            "local enterprises are supported to adopt better processing technologies",
            "the project facilitates access to digital tools for data collection and reporting",
            "farmers are linked to certified value chains requiring higher standards",
            "the project encourages use of mobile applications for extension services",
            "storage infrastructure is improved to reduce post harvest losses",
            "the project helps organize small producers into legally recognized cooperatives",
            "technical assistance is provided to upgrade production facilities",
            "innovation grants support adoption of climate smart technologies",
            "the project participates in pilots of new remote sensing approaches",
            "rural infrastructure is repaired or maintained to support sustainable production",
            "the project encourages experimentation with new agroforestry designs",
            "processing units adopt cleaner and more efficient energy sources",
            "the project helps connect remote communities to communication networks",
            "local artisans innovate new products based on non timber forest resources",
            "data management systems are established for long term project monitoring",
            "the project fosters collaboration between researchers and local producers",
            "climate resilient infrastructure is promoted in vulnerable areas",
            "the project supports simple irrigation infrastructure for smallholder plots",
            "experimentation with new tree species or seed sources is documented",
            "local entrepreneurs are trained in product development and marketing",
            "the project uses innovative approaches to participatory mapping",
            "infrastructure investments are assessed for environmental sustainability",
            "pilot initiatives test new approaches before wider rollout",
            "innovation is encouraged through competitions or calls for ideas",
            "the project helps producers meet standards required by responsible buyers",
            "community based enterprises access equipment through revolving funds",
            "the project collaborates with technical institutes on research and development",
            "infrastructure upgrades facilitate transport of legal and sustainable products",
            "the project encourages low cost innovations suitable for local conditions",
            "monitoring systems combine ground data with satellite information",
            "improved physical and digital infrastructure supports project objectives",
            "experiences from the project inform wider innovations in the sector",
            "support to basic infrastructure is linked to conservation commitments",
            "the project facilitates technology transfer to local organizations",
            "new business models for ecosystem services are tested in the landscape",
            "the project encourages reliable and resilient rural infrastructure",
            "producers adopt improved tools and equipment for efficient production",
            "innovative financing mechanisms are explored to sustain activities",
            "data collected in the project improves understanding of forest dynamics",
            "the project contributes to building local capacity in technical fields",
            "supply chain infrastructure is strengthened to reduce waste and losses",
            "lessons on innovation are documented and shared with partners",
            "infrastructure improvements explicitly support sustainable land use",
            "overall the project stimulates innovation and better infrastructure in rural areas"
        ]
    },

    # =========================================================
    # SDG 10 — REDUCED INEQUALITIES
    # =========================================================
    "SDG_10_Reduced_Inequalities": {
        "example_sentences": [
            "the project explicitly targets marginalized groups for participation",
            "indigenous peoples are recognized as key stakeholders in the project area",
            "benefit sharing arrangements consider the needs of poorer households",
            "the project helps remote communities access markets and services",
            "participation records show involvement of socially excluded groups",
            "livelihood support is prioritized for households with limited assets",
            "the project addresses unequal access to forest resources among community members",
            "information is provided in formats accessible to people with low literacy",
            "the project designs activities to be inclusive of persons with disabilities",
            "care is taken to ensure elites do not capture project benefits",
            "the project conducts outreach to minority ethnic or language groups",
            "benefits are distributed in ways that avoid reinforcing existing inequalities",
            "the project helps bridge gaps between customary and formal institutions",
            "support is provided to ensure women headed households are not left behind",
            "landless households are considered in livelihood program design",
            "the project monitors who benefits and adjusts to reduce disparities",
            "decision making processes are open to all segments of the community",
            "the project reduces inequalities between forest fringe and central villages",
            "grievance mechanisms are available and accessible to vulnerable groups",
            "specific measures address historical exclusion of indigenous communities",
            "youth from marginalized backgrounds are offered training opportunities",
            "the project supports fair representation in committees and leadership roles",
            "benefit sharing formulas are explained transparently to all stakeholders",
            "the project helps households with less land access off farm opportunities",
            "support is available in local languages spoken by minority groups",
            "the project reduces inequality in access to extension and credit services",
            "monitoring data are disaggregated by gender, ethnicity and wealth where possible",
            "the project seeks to reduce wealth gaps exacerbated by previous interventions",
            "consultations include groups that are often overlooked in planning processes",
            "the project aims to prevent displacement or exclusion of poorer residents",
            "efforts are made to ensure fair inclusion of migrant populations when relevant",
            "the project contributes to leveling opportunities across different social groups",
            "targeted support is provided to especially vulnerable households",
            "the project addresses power imbalances in natural resource governance",
            "activities are designed so that benefits are not limited to better connected groups",
            "mechanisms exist to challenge unfair practices related to resource access",
            "the project works with local authorities to support equitable policies",
            "participation frameworks emphasize inclusion and equal voice for all",
            "the project helps reduce disparities between upstream and downstream users",
            "support to producer organizations includes smaller or less advantaged members",
            "the project challenges discriminatory norms that limit participation of some groups",
            "differential impacts on wealth groups are considered in project design",
            "the project supports improved access to information for remote households",
            "specific gender and social inclusion plans are implemented and monitored",
            "the project narrows gaps between communities with and without forest resources",
            "attention is paid to fairness in labour opportunities under the project",
            "policy engagement considers the rights of marginalized communities",
            "overall the project contributes to reducing social and economic inequalities"
        ]
    },

    # =========================================================
    # SDG 11 — SUSTAINABLE CITIES AND COMMUNITIES
    # =========================================================
    "SDG_11_Sustainable_Communities": {
        "example_sentences": [
            "the project enhances resilience of rural settlements to climate related hazards",
            "forest restoration reduces landslide risk affecting nearby communities",
            "the project supports community level disaster risk management planning",
            "tree planting around villages provides shade and improves local conditions",
            "the project reduces the likelihood of damaging wildfires near settlements",
            "community infrastructure such as paths and footbridges is maintained",
            "the project contributes to safer and more liveable rural environments",
            "settlement planning incorporates conservation of nearby forest patches",
            "the project supports upgrading of community meeting spaces and facilities",
            "green spaces and communal woodlots are established near villages",
            "the project integrates local development priorities with conservation goals",
            "community members participate in planning land use around settlements",
            "firebreaks and fuel management reduce risk to homes and infrastructure",
            "the project addresses pressures from urban expansion into forest areas",
            "support is given to improve housing through income from project activities",
            "rural communities are better prepared for extreme weather events",
            "the project helps maintain ecosystem services that support local towns",
            "improved road drainage reduces damage to rural infrastructure",
            "community heritage and cultural sites are protected within the landscape",
            "the project encourages sustainable building materials from managed forests",
            "land use plans reduce uncontrolled sprawl into sensitive areas",
            "the project supports safer access routes for collecting forest products",
            "communities use project forums to discuss broader development needs",
            "rural to urban migration pressures may be reduced by new local opportunities",
            "urban water supplies benefit from restored upstream catchments",
            "the project coordinates with local authorities responsible for planning",
            "village by laws integrate environmental and settlement management issues",
            "ecosystem based approaches are used to protect communities from hazards",
            "the project considers disaster risk when locating new infrastructure",
            "communities report improved safety due to better fire management",
            "the project supports upgrades to public facilities using sustainable materials",
            "plans for expansion of settlements consider high conservation value areas",
            "the project encourages sustainable transport options for local communities",
            "awareness campaigns highlight the role of forests in supporting settlements",
            "settlement level committees manage communal resources and services",
            "improved waste management practices are promoted alongside other activities",
            "the project addresses risks posed by floods to roads and homes",
            "community consultations address housing and service access inequalities",
            "the project promotes compact and efficient use of land around villages",
            "rural communities are integrated into wider landscape planning processes",
            "project activities strengthen the social fabric and cohesion in settlements",
            "local governance structures are better equipped to support sustainable communities",
            "the project recognizes the importance of cultural values in settlement design",
            "engagement extends to peri urban communities dependent on nearby forests",
            "the project helps balance conservation with development around growing towns",
            "evidence indicates improved resilience of communities to environmental shocks",
            "infrastructure works are designed not to increase risk in vulnerable locations",
            "the project demonstrates how rural communities can develop sustainably",
            "overall the project supports safer and more sustainable human settlements"
        ]
    },

    # =========================================================
    # SDG 12 — RESPONSIBLE CONSUMPTION AND PRODUCTION
    # =========================================================
    "SDG_12_Responsible_Consumption": {
        "example_sentences": [
            "the project promotes sustainable harvesting of non timber forest products",
            "management plans set quotas for resource use based on regeneration rates",
            "the project discourages wasteful use of fuelwood and other biomass",
            "training stresses the importance of using all parts of harvested products",
            "the project supports certification schemes that reward sustainable production",
            "community members adopt practices that reduce post harvest losses",
            "agricultural practices reduce reliance on harmful agrochemicals",
            "the project encourages composting and recycling of organic waste",
            "supply chains prioritize environmentally responsible buyers and processors",
            "the project promotes efficient use of water and nutrients on farms",
            "unsustainable charcoal production is replaced by improved technologies",
            "the project raises awareness about responsible consumer choices",
            "local markets begin to offer more sustainably produced goods",
            "waste from processing facilities is managed to reduce pollution",
            "the project supports community rules against overexploitation of wildlife",
            "agroforestry systems reduce pressure on remaining natural forests",
            "producers are trained to meet standards for sustainable commodities",
            "the project encourages transparent labelling of sustainably sourced products",
            "monitoring tracks compliance with sustainable harvesting guidelines",
            "the project urges reduced use of single use plastics at community events",
            "training emphasizes long term resource stewardship over short term gain",
            "households adopt energy and resource saving practices promoted by the project",
            "the project discourages clearing of forest for unsustainable monocultures",
            "improved storage reduces spoilage of agricultural produce",
            "community members report reduced waste in utilization of forest products",
            "resource use decisions are informed by data on stock and regeneration",
            "the project supports adoption of integrated pest management approaches",
            "value chains supported by the project minimize waste along the chain",
            "the project addresses unsustainable grazing practices in forest areas",
            "consumption patterns in local enterprises shift towards sustainable inputs",
            "producers receive training on quality standards and reduced contamination",
            "community bylaws control unsustainable extraction of sand or stone",
            "the project demonstrates sustainable models for timber production where relevant",
            "forests are zoned for different uses to avoid over concentration of impacts",
            "the project supports reduced burning of residues that could be used productively",
            "long term resource use plans account for both current and future needs",
            "local culture of stewardship is strengthened through project activities",
            "producers commit to codes of practice for sustainable production",
            "the project supports inventories of resources to guide responsible use",
            "awareness campaigns discuss global impacts of unsustainable consumption",
            "behaviour change communication encourages careful use of scarce resources",
            "the project reduces illegal extraction that depletes natural capital",
            "value addition in processing aims to maximize use of each unit of resource",
            "feedback from buyers encourages further improvements in sustainability",
            "the project highlights examples of households adopting responsible practices",
            "support for circular approaches reduces waste from inputs and outputs",
            "communities report pride in producing responsibly sourced products",
            "the project clearly promotes more responsible modes of production and use"
        ]
    },

    # =========================================================
    # SDG 13 — CLIMATE ACTION
    # =========================================================
    "SDG_13_Climate_Action": {
        "example_sentences": [
            "the project increases awareness of climate change impacts among communities",
            "training is provided on adaptation measures for local farming systems",
            "the project strengthens capacity to manage climate related forest risks",
            "communities participate in planning for climate resilient land use",
            "the project monitors climate related indicators such as rainfall patterns",
            "adaptation actions are integrated into local development plans",
            "the project supports diversification of livelihoods to reduce climate risk",
            "fire management strategies reduce vulnerability to climate driven wildfires",
            "the project contributes to building resilience to drought in the landscape",
            "awareness campaigns explain the link between forests and climate regulation",
            "communities receive information on early warning systems where available",
            "the project encourages water conservation in response to changing rainfall",
            "climate risk assessments inform project design and implementation",
            "the project supports climate smart practices in agriculture and forestry",
            "community members report greater understanding of climate variability",
            "institutional capacity to respond to climate shocks is strengthened",
            "the project documents lessons on climate adaptation for wider sharing",
            "reforestation and restoration help buffer communities from climate extremes",
            "the project encourages use of climate forecasts in planning farm activities",
            "activities contribute to national climate strategies and adaptation plans",
            "local knowledge on coping with climate is integrated into project approaches",
            "the project addresses specific vulnerabilities such as flood prone areas",
            "capacity building includes training for local officials on climate issues",
            "the project supports climate resilient infrastructure in rural areas",
            "monitoring data help understand climate trends at the project site",
            "the project promotes discussions on long term climate scenarios",
            "activities consider both mitigation and adaptation benefits of forests",
            "communities report being better prepared for climate related shocks",
            "the project links community action with national climate reporting processes",
            "forest protection reduces emissions and supports long term climate goals",
            "climate related risks are regularly reviewed as part of project management",
            "the project helps reduce climate sensitivity of local livelihoods",
            "awareness materials explain how project actions contribute to climate goals",
            "the project coordinates with government climate change units",
            "lessons are shared with other initiatives working on climate resilience",
            "activities enhance carbon sinks while supporting adaptation outcomes",
            "the project engages youth in climate action activities and campaigns",
            "community bylaws incorporate climate considerations into resource use rules",
            "the project supports insurance or risk sharing mechanisms when feasible",
            "climate adaptation indicators are included in the monitoring framework",
            "participants understand how land use choices affect future climate risks",
            "the project responds to observed changes in temperature and rainfall",
            "capacity is built for climate sensitive planning at local level",
            "project reports highlight adaptation co benefits alongside emissions reductions",
            "the project supports landscape level planning for climate resilience",
            "evidence suggests reduced vulnerability to climate related disasters",
            "community narratives describe improved coping strategies for climate impacts",
            "climate action is an explicit objective of the project design and reporting"
        ]
    },

    # =========================================================
    # SDG 14 — LIFE BELOW WATER
    # =========================================================
    "SDG_14_Life_Below_Water": {
        "example_sentences": [
            "the project restores mangrove forests along coastal zones",
            "improved mangrove cover provides nursery habitat for fish and crustaceans",
            "the project reduces sedimentation into coastal waters from upstream erosion",
            "communities report improved coastal fisheries near restored mangroves",
            "protecting riparian zones reduces pollution entering rivers and lakes",
            "the project discourages dumping of waste into streams and waterways",
            "wetland restoration enhances habitat for aquatic species",
            "the project supports sustainable management of community fishing areas",
            "training is provided on responsible fishing practices in adjacent waters",
            "reduced use of harmful agrochemicals benefits downstream aquatic ecosystems",
            "the project helps maintain flows needed to sustain wetlands and estuaries",
            "buffer zones are established along waterways to protect aquatic life",
            "forest conservation in headwaters reduces impacts on downstream reefs",
            "community members observe clearer water in rivers after erosion control",
            "the project coordinates with marine conservation groups where relevant",
            "activities reduce pollution loads entering coastal and freshwater systems",
            "the project monitors indicators relevant to water quality and aquatic health",
            "mangrove planting reduces coastal erosion that affects nearshore habitats",
            "the project raises awareness about the importance of mangroves for fisheries",
            "upstream interventions support ecosystems connected to marine environments",
            "community rules restrict activities that degrade riverbanks and shorelines",
            "the project supports integrated management of catchments and coastal areas",
            "restored mangroves provide habitat for birds and aquatic organisms",
            "reductions in sediment export benefit seagrass and coral systems downstream",
            "support is given to alternative livelihoods that reduce pressure on fisheries",
            "the project reduces impacts from uncontrolled runoff into water bodies",
            "environmental education covers linkages between forests and aquatic systems",
            "the project considers impacts on fish migration routes along rivers",
            "improved land management practices reduce algal blooms in lakes",
            "coastal communities benefit from enhanced storm protection by mangroves",
            "monitoring of mangrove plots tracks recovery of coastal ecosystems",
            "the project addresses threats to wetlands important for fish breeding",
            "training materials highlight ecosystem services provided by aquatic habitats",
            "protecting source areas for rivers supports life in downstream waters",
            "the project reduces cutting of mangrove wood for charcoal and fuel",
            "sustainable harvesting practices in mangroves are promoted where allowed",
            "the project helps enforce regulations on pollution of aquatic environments",
            "stakeholders recognize benefits of upstream forest protection for fisheries",
            "the project contributes to maintaining biodiversity in coastal lagoons",
            "activities reduce threats to endangered aquatic species in connected systems",
            "remote sensing is used to monitor mangrove and wetland extent over time",
            "the project highlights co benefits for marine and freshwater ecosystems",
            "communities participate in mapping and protecting critical aquatic habitats",
            "interventions align with national plans for managing water and marine areas",
            "the project clearly supports healthier aquatic ecosystems through land action"
        ]
    },

    # =========================================================
    # SDG 15 — LIFE ON LAND
    # =========================================================
    "SDG_15_Life_On_Land": {
        "example_sentences": [
            "the project protects large areas of natural forest from deforestation",
            "biodiversity surveys document species present within the project area",
            "the project restores degraded lands with native tree species",
            "wildlife corridors are maintained or enhanced as part of the project design",
            "measures are taken to prevent illegal hunting and poaching in the area",
            "the project includes monitoring of key indicator species over time",
            "forest patrols help detect and prevent encroachment into intact habitats",
            "the project reduces degradation from uncontrolled fire and grazing",
            "restoration sites are selected to maximize ecological connectivity",
            "the project supports natural regeneration of forests where appropriate",
            "high conservation value areas are identified and strictly protected",
            "management plans incorporate biodiversity conservation objectives",
            "the project reduces soil erosion on slopes and fragile lands",
            "communities participate in activities that enhance local ecosystems",
            "tree species used for planting are adapted and often indigenous to the area",
            "biodiversity co benefits are described and reported in project documents",
            "invasive species management is addressed in restoration activities",
            "the project supports habitat for threatened or endemic species",
            "land use zoning distinguishes conservation, use and restoration areas",
            "the project reduces fragmentation of forest blocks in the landscape",
            "monitoring data show improvements in forest condition indicators",
            "safeguards ensure that project activities do not harm important habitats",
            "the project collaborates with conservation organizations in the region",
            "community awareness of wildlife protection is raised through education",
            "forest structure and biomass are measured as part of monitoring protocols",
            "the project addresses drivers of degradation such as illegal timber extraction",
            "maps show expansion of forest cover due to project interventions",
            "the project promotes sustainable use of non timber forest resources",
            "soil and vegetation cover improve in areas previously degraded",
            "the project reduces expansion of agriculture into forest frontiers",
            "management activities aim to maintain ecosystem functions and services",
            "camera traps or other tools are used to monitor wildlife presence",
            "the project contributes to national biodiversity and land degradation targets",
            "forest governance structures help enforce rules protecting ecosystems",
            "training covers identification and protection of key flora and fauna",
            "project design includes buffer zones around particularly sensitive sites",
            "impacts on biodiversity are considered in all major project decisions",
            "land degradation neutrality is supported through restoration activities",
            "communities recognize the value of wildlife and forests to their livelihoods",
            "the project achieves measurable reductions in deforestation rates",
            "habitat quality improves in areas previously subject to heavy use",
            "the project documents changes in species composition and abundance",
            "land use conflicts are reduced through agreed rules and boundary demarcation",
            "the project supports long term stewardship of forest and woodland areas",
            "safeguard plans mitigate risks to biodiversity during implementation",
            "results show positive trends in vegetation indices at the landscape scale",
            "conservation of natural ecosystems is a central objective of the project",
            "overall the project clearly enhances terrestrial ecosystems and biodiversity"
        ]
    },

    # =========================================================
    # SDG 16 — PEACE, JUSTICE AND STRONG INSTITUTIONS
    # =========================================================
    "SDG_16_Peace_Justice_Institutions": {
        "example_sentences": [
            "the project strengthens local institutions responsible for forest governance",
            "transparent processes are used to select members of management committees",
            "bylaws for resource use are developed through inclusive community meetings",
            "the project establishes clear rules for benefit sharing and decision making",
            "grievance mechanisms allow stakeholders to raise concerns and seek redress",
            "conflict resolution training is provided to community leaders",
            "the project helps reduce conflicts over land and resource boundaries",
            "documentation of land rights is supported where appropriate",
            "the project coordinates with government agencies on enforcement of regulations",
            "meeting minutes and financial records are shared with community members",
            "the project promotes accountability in use of project funds",
            "representation in project committees reflects different social groups",
            "law enforcement officials are trained on environmental legislation",
            "participatory mapping helps clarify tenure and reduce disputes",
            "the project respects customary institutions while promoting inclusion",
            "decisions are made according to agreed procedures rather than elite capture",
            "the project supports efforts to address illegal logging and associated crime",
            "local regulations are harmonized with national forest and land laws",
            "communities report fewer disputes related to project activities",
            "the project encourages open dialogue between communities and authorities",
            "governance assessments are conducted to identify institutional strengths and gaps",
            "safeguard frameworks protect rights of indigenous and local communities",
            "the project supports legal recognition of community forest user groups",
            "gender balanced representation is encouraged in local decision bodies",
            "monitoring includes indicators related to governance performance",
            "the project supports civic engagement on environmental issues",
            "mechanisms exist for periodic review of rules and benefit sharing",
            "the project operates in line with free prior and informed consent principles",
            "logging and land conversion permits are scrutinized against legal standards",
            "the project works to reduce corruption risks in forest and land sectors",
            "stakeholders have access to information about project objectives and impacts",
            "the project helps clarify institutional roles in land use management",
            "agreements between communities and project developers are documented",
            "training is provided on rights and responsibilities under relevant laws",
            "the project contributes to stronger trust between communities and state actors",
            "formal and informal institutions collaborate more effectively through the project",
            "local committees are empowered to oversee natural resource management",
            "project staff follow clear ethical guidelines in their engagement",
            "community monitoring contributes to enforcement of agreed rules",
            "the project reduces incentives for illegal activities that fuel conflict",
            "governance improvements are documented and shared with partners",
            "multi stakeholder platforms provide space for dialogue on landscape issues",
            "the project upholds principles of fairness and justice in its operations",
            "institutional capacity is built to manage forests beyond the project period",
            "decisions affecting local people are made transparently and with consultation",
            "project design considers risks of exacerbating existing tensions",
            "clear documentation of consent and agreements is maintained",
            "overall the project promotes more peaceful and effective local institutions"
        ]
    },

    # =========================================================
    # SDG 17 — PARTNERSHIPS FOR THE GOALS
    # =========================================================
    "SDG_17_Partnerships": {
        "example_sentences": [
            "the project is implemented through partnerships between communities and NGOs",
            "government agencies collaborate actively in project planning and oversight",
            "the project secures co financing from multiple international donors",
            "private sector actors are engaged to support sustainable value chains",
            "technical institutes provide research and monitoring support to the project",
            "the project aligns with national strategies and involves relevant ministries",
            "community based organizations are formal partners in implementation",
            "collaboration takes place with other projects in the same landscape",
            "data and lessons are shared with regional and global initiatives",
            "the project participates in multi stakeholder platforms on climate and forests",
            "partnership agreements outline roles and responsibilities of each actor",
            "international standards bodies are engaged for certification processes",
            "the project leverages partnerships to access new technologies and tools",
            "local authorities are involved in approving and supporting project plans",
            "partnerships with finance institutions support long term sustainability",
            "the project coordinates with NGOs working on related social issues",
            "civil society organizations help monitor social and environmental safeguards",
            "the project contributes data to national forest monitoring systems",
            "knowledge exchange visits are organized with other project sites",
            "partnerships support capacity building at community and institutional levels",
            "the project builds on previous initiatives rather than working in isolation",
            "agreements with private companies require adherence to sustainability criteria",
            "international organizations provide technical backstopping to the project",
            "communities are recognized as equal partners rather than only beneficiaries",
            "the project reports on partnerships as part of its documentation",
            "joint planning sessions are held with multiple stakeholders involved in the area",
            "coordination reduces duplication of efforts among different programs",
            "the project contributes expertise to policy dialogues at national level",
            "multi sector partnerships address both environmental and social challenges",
            "the project mobilizes additional resources through strategic alliances",
            "local universities and researchers are partners in field studies and analysis",
            "the project aligns monitoring frameworks with national and global indicators",
            "memorandums of understanding formalize collaboration between institutions",
            "the project seeks synergies with broader landscape and jurisdictional efforts",
            "cross boundary collaboration occurs with neighbouring administrative areas",
            "international networks share project experiences across countries",
            "the project benefits from partnerships that combine different strengths",
            "stakeholders co design activities to achieve shared objectives",
            "the project engages corporate buyers committed to responsible sourcing",
            "dialogue with government improves enabling conditions for scaling up",
            "partnerships include both formal agreements and informal working relationships",
            "the project’s success depends on strong collaboration among many actors",
            "evidence of joint planning and implementation is documented in reports",
            "partners help advocate for supportive policies and regulations",
            "the project strengthens local capacities to engage in future partnerships",
            "long term partnerships are envisaged beyond the duration of initial funding",
            "overall the project clearly operates through and strengthens partnerships for sustainable development"
        ]
    }
}
